src/globalStatusBar/globalStatusBar.js
src/index.js
src/sidenav/sidenav.js

Add sidebar navigation

---

src/globalStatusBar/lib/libTransition.js
src/globalStatusBar/login/loginDialog.js
src/globalStatusBar/userSetting/passwordChange/passwordChangeDialog.js
src/globalStatusBar/userSetting/userSettingDialog.js

Removing warnings during React development server's compilation

Removing unneeded import statements

---

src/app/submissions/stub/submission.js
src/app/submissions/submissionDetail/testBasedVerdictTable.js
src/app/submissions/submissionTable.js
src/app/submissions/submissionWrapper.js

- Only reload once when constructing instead of using `componentWillMount`
- Fix glitch bug where component VerdictSignature isn't update
- Cover submissionParse when user not login

Page 2nd fix

---

src/app/globalStatusBar/login/stub/credential.js
src/app/globalStatusBar/login/stub/login.js

Removing call to update submission table upon logging in

---

src/app/about/about.js
src/app/about/aboutLauncher.js
src/app/home/homepage.js
src/app/scoreboard/scoreboard.js

Scoreboard : Fix warning about arrow functions not returning a value

---

src/app/globalStatusBar/login/stub/login.js
src/app/globalStatusBar/userSetting/passwordChange/passwordChangeDialog.js
src/app/globalStatusBar/userSetting/stub/passwordChange.js

Integrating the ability to change password

---

src/app/home/homepageLauncher.js
src/app/problemList/problemLauncher.js
src/app/scoreboard/scoreboardLauncher.js
src/app/submissions/submissionLauncher.js

_Now that the code has become stable, this PR will start a series of cosmetic changes. `#1`._
The old `Send` icon is pretty non-descriptive and repeating. A new icon has been chosen for each item.

Changing thumbnails for drawer items

---

package.json
src/app/globalStatusBar/clock/clock.js
src/app/globalStatusBar/globalStatusBar.js
src/app/submissions/submission.js
src/external/timeAgo.js
src/index.js

Changing time format

---

src/app/globalStatusBar/clock/clock.js
src/app/globalStatusBar/globalStatusBar.js

Clock : now shows no duplicate text upon contest ended

---

src/app/globalStatusBar/clock/clock.js
src/app/globalStatusBar/globalStatusBar.js
src/index.js

Fixes #67.
Note that this requires the target branch to have https://github.com/vnma0/hestia/pull/69/commits/612b31ab37b5938187a1752f138369ee78c4eaf3 and ****no** commit **after** it changes** ` src/app/globalStatusBar/clock/clock.js`, `src/app/globalStatusBar/globalStatusBar.js` and `src/index.js`

Clock : let it calculate itself the time delta

---

src/app/globalStatusBar/clock/clock.css
src/app/globalStatusBar/clock/clock.js

Resolves #82.
_Cosmetic change, `#2`._

Add clock tooltip

---

src/app/scoreboard/scoreboard.js

Resolves #77.
_Cosmetic change, `#3`._

Score rounding

---

src/app/sidenav/sidenav.js
src/index.js

Hestia : no longer forces a full reload upon changing route

---

src/app/submissions/signature/verdictSignature.js
src/app/submissions/stub/submission.js

Keep up with verdict changes

---

src/app/problemList/codeEditor/extParser.js

Improve extParser.js

---

src/app/submissions/stub/submission.js
src/app/submissions/submissionWrapper.js

~This is not Windows 10~
Closes #70.
`/api/subs` will be regularly checked with new data and users will be informed if there's any, with an ability to trigger updating.
~ EDIT : not ready yet.~

Submissions page now tells user to update

---

src/app/submissions/submissionDetail/codePanel/codePanel.js

`CodePanel` : Show that it's loading when it's *really* loading

Make some things responsive

---

src/app/submissions/submission.css
src/app/submissions/submission.js

Fix non-functional exit button in submission details.
Closes #89.
_Cosmetic change, `#4`._

Add some color to Submissions page

---

src/app/home/homepage.js
src/app/problemList/problemWrapper.js
src/app/scoreboard/scoreboardWrapper.js
src/app/submissions/submissionWrapper.js
src/index.js

Change page title when route changes

---

src/app/problemList/codeEditor/codeBox.js

Fixing faulty comparison leading to faulty file-loading

---

src/app/problemList/codeEditor/codeBox.js

Allow re-uploading same file

---

src/app/problemList/codeEditor/codeBox.js

First spotted in 81639531d0dd0c843d306aeea5332377cbad4cee.

Covering lifecycle event to prevent memory leak

---

README.md
doc/README.vi-VN.md
package.json
prettier.config.js

Prettify what users don't see

---

src/app/scoreboard/scoreboard.css
src/app/scoreboard/scoreboard.js

Colourful scoreboard

---

src/app/scoreboard/scoreboard.js
src/app/scoreboard/scoreboardWrapper.js

ACM support for scoreboard

---

package.json
scripts/gzip-all.js

Adding gzip build production script

---

src/app/scoreboard/scoreboard.css
src/app/scoreboard/scoreboardWrapper.js

~@dungwinux, should we allow variable update interval?~
Well nope, I won't allow manual self-triggerable update and customized interval support at the same time - race conditions can break things.

Update scores manually

---

src/app/loggedOut.js
src/index.js

Blocking all user activities if not logged in

---

src/app/problemList/codeEditor/codeBox.js
src/index.js

This saves users from accidentally pressing F5.

Enable support for LocalStorage to save code

---

src/app/globalStatusBar/clock/clock.css
src/app/globalStatusBar/globalStatusBar.js
src/app/globalStatusBar/userSetting/userSettingButton.css
src/app/globalStatusBar/userSetting/userSettingButton.js
src/index.css
src/index.js

@dungwinux, if you have time, mind checking it out?<br>I'm including [a compiled build](https://github.com/vnma0/hestia/files/3165518/hestia-standalone-untagged-1.5.5.zip) here, and [here](https://github.com/vnma0/hestia/files/3165559/wafter.zip) is a build of [Wafter](https://github.com/vnma0/wafter) with it included.
In short, these are the changes :

Rounded stuff

---

src/app/submissions/submission.js
src/app/submissions/submissionDetail/codePanel/codePanel.js
src/app/submissions/submissionDetail/submissionDetail.js
src/app/submissions/submissionDetail/testBasedVerdictTable.js
src/app/submissions/submissionTable.js
src/app/submissions/submissionWrapper.js

Changelog :
- Display the total score awarded if any.
- Support for memory consumption displaying has been hidden and disabled.
- The maximum time used for execution will be displayed.
- Closes #150.

Little enhancements
